#!/bin/bash
# scripts/99-cleanup.sh
# Template sealing script — runs last in every Packer build.
# Removes per-instance state so the template is clean for cloning.
# Must be run as root (Packer uses: sudo -S bash {{.Path}})

set -euo pipefail

echo "========================================"
echo " 99-cleanup.sh: sealing template"
echo "========================================"

# ── Remove SSH host keys ───────────────────────────────────────────────────────
# New keys are regenerated by the OS on first boot of each cloned VM.
echo "[1/8] Removing SSH host keys..."
rm -f /etc/ssh/ssh_host_*
echo "SSH host keys removed"

# ── Reset cloud-init ──────────────────────────────────────────────────────────
# Ensures cloud-init runs fully on first boot of each cloned VM.
echo "[2/8] Resetting cloud-init state..."
cloud-init clean --logs --seed
rm -rf /var/lib/cloud/*
echo "cloud-init state reset"

# ── Remove the Packer sudo rule ───────────────────────────────────────────────
echo "[3/8] Removing Packer sudoers rule..."
rm -f /etc/sudoers.d/kali-packer
echo "Packer sudoers rule removed"

# ── Clear logs ────────────────────────────────────────────────────────────────
echo "[4/8] Clearing system logs..."
find /var/log -type f -name "*.log" -exec truncate -s 0 {} \;
find /var/log -type f -name "*.gz" -delete
find /var/log -type f -name "*.[0-9]" -delete
truncate -s 0 /var/log/syslog      2>/dev/null || true
truncate -s 0 /var/log/auth.log    2>/dev/null || true
truncate -s 0 /var/log/kern.log    2>/dev/null || true
truncate -s 0 /var/log/dpkg.log    2>/dev/null || true
truncate -s 0 /var/log/apt/history.log 2>/dev/null || true
echo "Logs cleared"

# ── Clear shell history ───────────────────────────────────────────────────────
echo "[5/8] Clearing shell history..."
rm -f /root/.bash_history
rm -f /home/kali/.bash_history
history -c || true
cat /dev/null > ~/.bash_history
echo "Shell history cleared"

# ── Clear temp files ──────────────────────────────────────────────────────────
echo "[6/8] Clearing temp files..."
rm -rf /tmp/*
rm -rf /var/tmp/*
echo "Temp files cleared"

# ── Remove apt cache ──────────────────────────────────────────────────────────
echo "[7/8] Removing apt cache..."
apt-get autoremove -y -qq
apt-get autoclean -qq
rm -rf /var/lib/apt/lists/*
echo "Apt cache cleared"

# ── Zero free space (improves thin provisioning efficiency) ───────────────────
# Creates a zero-fill file to write zeros to all free blocks, then removes it.
# This makes the resulting OVA compress much better.
echo "[8/8] Zeroing free space (this takes a few minutes)..."
dd if=/dev/zero of=/zero.fill bs=4M status=progress 2>/dev/null || true
rm -f /zero.fill
sync
echo "Free space zeroed"

echo "========================================"
echo " 99-cleanup.sh: template sealed"
echo "========================================"
